################################################################################
# Automatically-generated file. Do not edit!
################################################################################

SHELL = cmd.exe

# Each subdirectory must supply rules for building sources it contributes
MW_c28xGPIO.obj: C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/shared/supportpackages/tic2000/src/MW_c28xGPIO.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccs1040/ccs/tools/compiler/ti-cgt-c2000_20.2.5.LTS/bin/cl2000" --include_path="C:/ti/ccs1040/ccs/tools/compiler/ti-cgt-c2000_20.2.5.LTS/include" --include_path="E:/Documents/OneDrive - bwedu/Uni/Master/Semester 1 - 2021/Machatronisches Projekt/Matlab" --include_path="E:/Documents/OneDrive - bwedu/Uni/Master/Semester 1 - 2021/Machatronisches Projekt/Matlab/RealTimeMachine_ert_rtw" --include_path="C:/Program Files/MATLAB/R2021a/extern/include" --include_path="C:/Program Files/MATLAB/R2021a/simulink/include" --include_path="C:/Program Files/MATLAB/R2021a/rtw/c/src" --include_path="C:/Program Files/MATLAB/R2021a/rtw/c/src/ext_mode/common" --include_path="C:/Program Files/MATLAB/R2021a/rtw/c/ert" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/target/supportpackages/tic2000/inc" --include_path="C:/Program Files/MATLAB/R2021a/toolbox/shared/can/src/scanutil" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/target/supportpackages/tic2000/src" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/shared/supportpackages/tic2000/src" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/shared/supportpackages/tic2000/inc" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/device_support/f28004x/common/include" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/libraries/calibration/hrpwm/f28004x/include" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/driverlib/f28004x/driverlib" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/driverlib/f28004x/driverlib/inc" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/device_support/f28004x/headers/include" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/device_support/f28004x/common" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/target/shared/externalmode_daemon/include" --include_path="C:/Program Files/MATLAB/R2021a/toolbox/rtw/targets/common/can/blocks/tlc_c" --define=MODEL=RealTimeMachine --define=NUMST=1 --define=NCSTATES=0 --define=HAVESTDIO --define=MODEL_HAS_DYNAMICALLY_LOADED_SFCNS=0 --define=CLASSIC_INTERFACE=0 --define=ALLOCATIONFCN=0 --define=TID01EQ=0 --define=TERMFCN=1 --define=ONESTEPFCN=1 --define=MAT_FILE=0 --define=MULTI_INSTANCE_CODE=0 --define=INTEGER_CODE=0 --define=MT=0 --define=DAEMON_MODE=1 --define=XCP_CUSTOM_PLATFORM --define=EXTMODE_DISABLE_ARGS_PROCESSING=1 --define=MW_PIL_SCIFIFOLEN=16 --define=CPU1 --define=F2837X_REG_FORMAT --define=MW_F28004X --define=STACK_SIZE=1024 --define=__MW_TARGET_USE_HARDWARE_RESOURCES_H__ --define=RT --define=F280049C --define=BOOT_FROM_FLASH=1 --abi=coffabi -s -v28 -ml --abi=coffabi  --preproc_dependency=$(@:%.obj=%.dep) --preproc_with_compile  --large_memory_model -I$(F28_HEADERS)/include -I$(TI_INCLUDE) -v28 --float_support=fpu32 -ml -DF280049C -DBOOT_FROM_FLASH=1 --tmu_support=tmu0 --fp_mode=relaxed --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

MW_c28xGlobalInterrupts.obj: C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/shared/supportpackages/tic2000/src/MW_c28xGlobalInterrupts.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccs1040/ccs/tools/compiler/ti-cgt-c2000_20.2.5.LTS/bin/cl2000" --include_path="C:/ti/ccs1040/ccs/tools/compiler/ti-cgt-c2000_20.2.5.LTS/include" --include_path="E:/Documents/OneDrive - bwedu/Uni/Master/Semester 1 - 2021/Machatronisches Projekt/Matlab" --include_path="E:/Documents/OneDrive - bwedu/Uni/Master/Semester 1 - 2021/Machatronisches Projekt/Matlab/RealTimeMachine_ert_rtw" --include_path="C:/Program Files/MATLAB/R2021a/extern/include" --include_path="C:/Program Files/MATLAB/R2021a/simulink/include" --include_path="C:/Program Files/MATLAB/R2021a/rtw/c/src" --include_path="C:/Program Files/MATLAB/R2021a/rtw/c/src/ext_mode/common" --include_path="C:/Program Files/MATLAB/R2021a/rtw/c/ert" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/target/supportpackages/tic2000/inc" --include_path="C:/Program Files/MATLAB/R2021a/toolbox/shared/can/src/scanutil" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/target/supportpackages/tic2000/src" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/shared/supportpackages/tic2000/src" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/shared/supportpackages/tic2000/inc" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/device_support/f28004x/common/include" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/libraries/calibration/hrpwm/f28004x/include" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/driverlib/f28004x/driverlib" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/driverlib/f28004x/driverlib/inc" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/device_support/f28004x/headers/include" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/device_support/f28004x/common" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/target/shared/externalmode_daemon/include" --include_path="C:/Program Files/MATLAB/R2021a/toolbox/rtw/targets/common/can/blocks/tlc_c" --define=MODEL=RealTimeMachine --define=NUMST=1 --define=NCSTATES=0 --define=HAVESTDIO --define=MODEL_HAS_DYNAMICALLY_LOADED_SFCNS=0 --define=CLASSIC_INTERFACE=0 --define=ALLOCATIONFCN=0 --define=TID01EQ=0 --define=TERMFCN=1 --define=ONESTEPFCN=1 --define=MAT_FILE=0 --define=MULTI_INSTANCE_CODE=0 --define=INTEGER_CODE=0 --define=MT=0 --define=DAEMON_MODE=1 --define=XCP_CUSTOM_PLATFORM --define=EXTMODE_DISABLE_ARGS_PROCESSING=1 --define=MW_PIL_SCIFIFOLEN=16 --define=CPU1 --define=F2837X_REG_FORMAT --define=MW_F28004X --define=STACK_SIZE=1024 --define=__MW_TARGET_USE_HARDWARE_RESOURCES_H__ --define=RT --define=F280049C --define=BOOT_FROM_FLASH=1 --abi=coffabi -s -v28 -ml --abi=coffabi  --preproc_dependency=$(@:%.obj=%.dep) --preproc_with_compile  --large_memory_model -I$(F28_HEADERS)/include -I$(TI_INCLUDE) -v28 --float_support=fpu32 -ml -DF280049C -DBOOT_FROM_FLASH=1 --tmu_support=tmu0 --fp_mode=relaxed --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

MW_c28xx_board.obj: E:/Documents/OneDrive\ -\ bwedu/Uni/Master/Semester\ 1\ -\ 2021/Machatronisches\ Projekt/Matlab/RealTimeMachine_ert_rtw/MW_c28xx_board.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccs1040/ccs/tools/compiler/ti-cgt-c2000_20.2.5.LTS/bin/cl2000" --include_path="C:/ti/ccs1040/ccs/tools/compiler/ti-cgt-c2000_20.2.5.LTS/include" --include_path="E:/Documents/OneDrive - bwedu/Uni/Master/Semester 1 - 2021/Machatronisches Projekt/Matlab" --include_path="E:/Documents/OneDrive - bwedu/Uni/Master/Semester 1 - 2021/Machatronisches Projekt/Matlab/RealTimeMachine_ert_rtw" --include_path="C:/Program Files/MATLAB/R2021a/extern/include" --include_path="C:/Program Files/MATLAB/R2021a/simulink/include" --include_path="C:/Program Files/MATLAB/R2021a/rtw/c/src" --include_path="C:/Program Files/MATLAB/R2021a/rtw/c/src/ext_mode/common" --include_path="C:/Program Files/MATLAB/R2021a/rtw/c/ert" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/target/supportpackages/tic2000/inc" --include_path="C:/Program Files/MATLAB/R2021a/toolbox/shared/can/src/scanutil" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/target/supportpackages/tic2000/src" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/shared/supportpackages/tic2000/src" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/shared/supportpackages/tic2000/inc" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/device_support/f28004x/common/include" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/libraries/calibration/hrpwm/f28004x/include" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/driverlib/f28004x/driverlib" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/driverlib/f28004x/driverlib/inc" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/device_support/f28004x/headers/include" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/device_support/f28004x/common" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/target/shared/externalmode_daemon/include" --include_path="C:/Program Files/MATLAB/R2021a/toolbox/rtw/targets/common/can/blocks/tlc_c" --define=MODEL=RealTimeMachine --define=NUMST=1 --define=NCSTATES=0 --define=HAVESTDIO --define=MODEL_HAS_DYNAMICALLY_LOADED_SFCNS=0 --define=CLASSIC_INTERFACE=0 --define=ALLOCATIONFCN=0 --define=TID01EQ=0 --define=TERMFCN=1 --define=ONESTEPFCN=1 --define=MAT_FILE=0 --define=MULTI_INSTANCE_CODE=0 --define=INTEGER_CODE=0 --define=MT=0 --define=DAEMON_MODE=1 --define=XCP_CUSTOM_PLATFORM --define=EXTMODE_DISABLE_ARGS_PROCESSING=1 --define=MW_PIL_SCIFIFOLEN=16 --define=CPU1 --define=F2837X_REG_FORMAT --define=MW_F28004X --define=STACK_SIZE=1024 --define=__MW_TARGET_USE_HARDWARE_RESOURCES_H__ --define=RT --define=F280049C --define=BOOT_FROM_FLASH=1 --abi=coffabi -s -v28 -ml --abi=coffabi  --preproc_dependency=$(@:%.obj=%.dep) --preproc_with_compile  --large_memory_model -I$(F28_HEADERS)/include -I$(TI_INCLUDE) -v28 --float_support=fpu32 -ml -DF280049C -DBOOT_FROM_FLASH=1 --tmu_support=tmu0 --fp_mode=relaxed --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

MW_c28xx_csl.obj: E:/Documents/OneDrive\ -\ bwedu/Uni/Master/Semester\ 1\ -\ 2021/Machatronisches\ Projekt/Matlab/RealTimeMachine_ert_rtw/MW_c28xx_csl.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccs1040/ccs/tools/compiler/ti-cgt-c2000_20.2.5.LTS/bin/cl2000" --include_path="C:/ti/ccs1040/ccs/tools/compiler/ti-cgt-c2000_20.2.5.LTS/include" --include_path="E:/Documents/OneDrive - bwedu/Uni/Master/Semester 1 - 2021/Machatronisches Projekt/Matlab" --include_path="E:/Documents/OneDrive - bwedu/Uni/Master/Semester 1 - 2021/Machatronisches Projekt/Matlab/RealTimeMachine_ert_rtw" --include_path="C:/Program Files/MATLAB/R2021a/extern/include" --include_path="C:/Program Files/MATLAB/R2021a/simulink/include" --include_path="C:/Program Files/MATLAB/R2021a/rtw/c/src" --include_path="C:/Program Files/MATLAB/R2021a/rtw/c/src/ext_mode/common" --include_path="C:/Program Files/MATLAB/R2021a/rtw/c/ert" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/target/supportpackages/tic2000/inc" --include_path="C:/Program Files/MATLAB/R2021a/toolbox/shared/can/src/scanutil" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/target/supportpackages/tic2000/src" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/shared/supportpackages/tic2000/src" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/shared/supportpackages/tic2000/inc" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/device_support/f28004x/common/include" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/libraries/calibration/hrpwm/f28004x/include" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/driverlib/f28004x/driverlib" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/driverlib/f28004x/driverlib/inc" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/device_support/f28004x/headers/include" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/device_support/f28004x/common" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/target/shared/externalmode_daemon/include" --include_path="C:/Program Files/MATLAB/R2021a/toolbox/rtw/targets/common/can/blocks/tlc_c" --define=MODEL=RealTimeMachine --define=NUMST=1 --define=NCSTATES=0 --define=HAVESTDIO --define=MODEL_HAS_DYNAMICALLY_LOADED_SFCNS=0 --define=CLASSIC_INTERFACE=0 --define=ALLOCATIONFCN=0 --define=TID01EQ=0 --define=TERMFCN=1 --define=ONESTEPFCN=1 --define=MAT_FILE=0 --define=MULTI_INSTANCE_CODE=0 --define=INTEGER_CODE=0 --define=MT=0 --define=DAEMON_MODE=1 --define=XCP_CUSTOM_PLATFORM --define=EXTMODE_DISABLE_ARGS_PROCESSING=1 --define=MW_PIL_SCIFIFOLEN=16 --define=CPU1 --define=F2837X_REG_FORMAT --define=MW_F28004X --define=STACK_SIZE=1024 --define=__MW_TARGET_USE_HARDWARE_RESOURCES_H__ --define=RT --define=F280049C --define=BOOT_FROM_FLASH=1 --abi=coffabi -s -v28 -ml --abi=coffabi  --preproc_dependency=$(@:%.obj=%.dep) --preproc_with_compile  --large_memory_model -I$(F28_HEADERS)/include -I$(TI_INCLUDE) -v28 --float_support=fpu32 -ml -DF280049C -DBOOT_FROM_FLASH=1 --tmu_support=tmu0 --fp_mode=relaxed --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

MW_c28xx_qep.obj: E:/Documents/OneDrive\ -\ bwedu/Uni/Master/Semester\ 1\ -\ 2021/Machatronisches\ Projekt/Matlab/RealTimeMachine_ert_rtw/MW_c28xx_qep.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccs1040/ccs/tools/compiler/ti-cgt-c2000_20.2.5.LTS/bin/cl2000" --include_path="C:/ti/ccs1040/ccs/tools/compiler/ti-cgt-c2000_20.2.5.LTS/include" --include_path="E:/Documents/OneDrive - bwedu/Uni/Master/Semester 1 - 2021/Machatronisches Projekt/Matlab" --include_path="E:/Documents/OneDrive - bwedu/Uni/Master/Semester 1 - 2021/Machatronisches Projekt/Matlab/RealTimeMachine_ert_rtw" --include_path="C:/Program Files/MATLAB/R2021a/extern/include" --include_path="C:/Program Files/MATLAB/R2021a/simulink/include" --include_path="C:/Program Files/MATLAB/R2021a/rtw/c/src" --include_path="C:/Program Files/MATLAB/R2021a/rtw/c/src/ext_mode/common" --include_path="C:/Program Files/MATLAB/R2021a/rtw/c/ert" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/target/supportpackages/tic2000/inc" --include_path="C:/Program Files/MATLAB/R2021a/toolbox/shared/can/src/scanutil" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/target/supportpackages/tic2000/src" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/shared/supportpackages/tic2000/src" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/shared/supportpackages/tic2000/inc" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/device_support/f28004x/common/include" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/libraries/calibration/hrpwm/f28004x/include" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/driverlib/f28004x/driverlib" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/driverlib/f28004x/driverlib/inc" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/device_support/f28004x/headers/include" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/device_support/f28004x/common" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/target/shared/externalmode_daemon/include" --include_path="C:/Program Files/MATLAB/R2021a/toolbox/rtw/targets/common/can/blocks/tlc_c" --define=MODEL=RealTimeMachine --define=NUMST=1 --define=NCSTATES=0 --define=HAVESTDIO --define=MODEL_HAS_DYNAMICALLY_LOADED_SFCNS=0 --define=CLASSIC_INTERFACE=0 --define=ALLOCATIONFCN=0 --define=TID01EQ=0 --define=TERMFCN=1 --define=ONESTEPFCN=1 --define=MAT_FILE=0 --define=MULTI_INSTANCE_CODE=0 --define=INTEGER_CODE=0 --define=MT=0 --define=DAEMON_MODE=1 --define=XCP_CUSTOM_PLATFORM --define=EXTMODE_DISABLE_ARGS_PROCESSING=1 --define=MW_PIL_SCIFIFOLEN=16 --define=CPU1 --define=F2837X_REG_FORMAT --define=MW_F28004X --define=STACK_SIZE=1024 --define=__MW_TARGET_USE_HARDWARE_RESOURCES_H__ --define=RT --define=F280049C --define=BOOT_FROM_FLASH=1 --abi=coffabi -s -v28 -ml --abi=coffabi  --preproc_dependency=$(@:%.obj=%.dep) --preproc_with_compile  --large_memory_model -I$(F28_HEADERS)/include -I$(TI_INCLUDE) -v28 --float_support=fpu32 -ml -DF280049C -DBOOT_FROM_FLASH=1 --tmu_support=tmu0 --fp_mode=relaxed --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

MW_c28xx_xbar.obj: E:/Documents/OneDrive\ -\ bwedu/Uni/Master/Semester\ 1\ -\ 2021/Machatronisches\ Projekt/Matlab/RealTimeMachine_ert_rtw/MW_c28xx_xbar.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccs1040/ccs/tools/compiler/ti-cgt-c2000_20.2.5.LTS/bin/cl2000" --include_path="C:/ti/ccs1040/ccs/tools/compiler/ti-cgt-c2000_20.2.5.LTS/include" --include_path="E:/Documents/OneDrive - bwedu/Uni/Master/Semester 1 - 2021/Machatronisches Projekt/Matlab" --include_path="E:/Documents/OneDrive - bwedu/Uni/Master/Semester 1 - 2021/Machatronisches Projekt/Matlab/RealTimeMachine_ert_rtw" --include_path="C:/Program Files/MATLAB/R2021a/extern/include" --include_path="C:/Program Files/MATLAB/R2021a/simulink/include" --include_path="C:/Program Files/MATLAB/R2021a/rtw/c/src" --include_path="C:/Program Files/MATLAB/R2021a/rtw/c/src/ext_mode/common" --include_path="C:/Program Files/MATLAB/R2021a/rtw/c/ert" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/target/supportpackages/tic2000/inc" --include_path="C:/Program Files/MATLAB/R2021a/toolbox/shared/can/src/scanutil" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/target/supportpackages/tic2000/src" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/shared/supportpackages/tic2000/src" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/shared/supportpackages/tic2000/inc" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/device_support/f28004x/common/include" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/libraries/calibration/hrpwm/f28004x/include" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/driverlib/f28004x/driverlib" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/driverlib/f28004x/driverlib/inc" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/device_support/f28004x/headers/include" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/device_support/f28004x/common" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/target/shared/externalmode_daemon/include" --include_path="C:/Program Files/MATLAB/R2021a/toolbox/rtw/targets/common/can/blocks/tlc_c" --define=MODEL=RealTimeMachine --define=NUMST=1 --define=NCSTATES=0 --define=HAVESTDIO --define=MODEL_HAS_DYNAMICALLY_LOADED_SFCNS=0 --define=CLASSIC_INTERFACE=0 --define=ALLOCATIONFCN=0 --define=TID01EQ=0 --define=TERMFCN=1 --define=ONESTEPFCN=1 --define=MAT_FILE=0 --define=MULTI_INSTANCE_CODE=0 --define=INTEGER_CODE=0 --define=MT=0 --define=DAEMON_MODE=1 --define=XCP_CUSTOM_PLATFORM --define=EXTMODE_DISABLE_ARGS_PROCESSING=1 --define=MW_PIL_SCIFIFOLEN=16 --define=CPU1 --define=F2837X_REG_FORMAT --define=MW_F28004X --define=STACK_SIZE=1024 --define=__MW_TARGET_USE_HARDWARE_RESOURCES_H__ --define=RT --define=F280049C --define=BOOT_FROM_FLASH=1 --abi=coffabi -s -v28 -ml --abi=coffabi  --preproc_dependency=$(@:%.obj=%.dep) --preproc_with_compile  --large_memory_model -I$(F28_HEADERS)/include -I$(TI_INCLUDE) -v28 --float_support=fpu32 -ml -DF280049C -DBOOT_FROM_FLASH=1 --tmu_support=tmu0 --fp_mode=relaxed --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

RealTimeMachine.obj: E:/Documents/OneDrive\ -\ bwedu/Uni/Master/Semester\ 1\ -\ 2021/Machatronisches\ Projekt/Matlab/RealTimeMachine_ert_rtw/RealTimeMachine.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccs1040/ccs/tools/compiler/ti-cgt-c2000_20.2.5.LTS/bin/cl2000" --include_path="C:/ti/ccs1040/ccs/tools/compiler/ti-cgt-c2000_20.2.5.LTS/include" --include_path="E:/Documents/OneDrive - bwedu/Uni/Master/Semester 1 - 2021/Machatronisches Projekt/Matlab" --include_path="E:/Documents/OneDrive - bwedu/Uni/Master/Semester 1 - 2021/Machatronisches Projekt/Matlab/RealTimeMachine_ert_rtw" --include_path="C:/Program Files/MATLAB/R2021a/extern/include" --include_path="C:/Program Files/MATLAB/R2021a/simulink/include" --include_path="C:/Program Files/MATLAB/R2021a/rtw/c/src" --include_path="C:/Program Files/MATLAB/R2021a/rtw/c/src/ext_mode/common" --include_path="C:/Program Files/MATLAB/R2021a/rtw/c/ert" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/target/supportpackages/tic2000/inc" --include_path="C:/Program Files/MATLAB/R2021a/toolbox/shared/can/src/scanutil" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/target/supportpackages/tic2000/src" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/shared/supportpackages/tic2000/src" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/shared/supportpackages/tic2000/inc" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/device_support/f28004x/common/include" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/libraries/calibration/hrpwm/f28004x/include" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/driverlib/f28004x/driverlib" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/driverlib/f28004x/driverlib/inc" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/device_support/f28004x/headers/include" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/device_support/f28004x/common" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/target/shared/externalmode_daemon/include" --include_path="C:/Program Files/MATLAB/R2021a/toolbox/rtw/targets/common/can/blocks/tlc_c" --define=MODEL=RealTimeMachine --define=NUMST=1 --define=NCSTATES=0 --define=HAVESTDIO --define=MODEL_HAS_DYNAMICALLY_LOADED_SFCNS=0 --define=CLASSIC_INTERFACE=0 --define=ALLOCATIONFCN=0 --define=TID01EQ=0 --define=TERMFCN=1 --define=ONESTEPFCN=1 --define=MAT_FILE=0 --define=MULTI_INSTANCE_CODE=0 --define=INTEGER_CODE=0 --define=MT=0 --define=DAEMON_MODE=1 --define=XCP_CUSTOM_PLATFORM --define=EXTMODE_DISABLE_ARGS_PROCESSING=1 --define=MW_PIL_SCIFIFOLEN=16 --define=CPU1 --define=F2837X_REG_FORMAT --define=MW_F28004X --define=STACK_SIZE=1024 --define=__MW_TARGET_USE_HARDWARE_RESOURCES_H__ --define=RT --define=F280049C --define=BOOT_FROM_FLASH=1 --abi=coffabi -s -v28 -ml --abi=coffabi  --preproc_dependency=$(@:%.obj=%.dep) --preproc_with_compile  --large_memory_model -I$(F28_HEADERS)/include -I$(TI_INCLUDE) -v28 --float_support=fpu32 -ml -DF280049C -DBOOT_FROM_FLASH=1 --tmu_support=tmu0 --fp_mode=relaxed --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

RealTimeMachine_data.obj: E:/Documents/OneDrive\ -\ bwedu/Uni/Master/Semester\ 1\ -\ 2021/Machatronisches\ Projekt/Matlab/RealTimeMachine_ert_rtw/RealTimeMachine_data.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccs1040/ccs/tools/compiler/ti-cgt-c2000_20.2.5.LTS/bin/cl2000" --include_path="C:/ti/ccs1040/ccs/tools/compiler/ti-cgt-c2000_20.2.5.LTS/include" --include_path="E:/Documents/OneDrive - bwedu/Uni/Master/Semester 1 - 2021/Machatronisches Projekt/Matlab" --include_path="E:/Documents/OneDrive - bwedu/Uni/Master/Semester 1 - 2021/Machatronisches Projekt/Matlab/RealTimeMachine_ert_rtw" --include_path="C:/Program Files/MATLAB/R2021a/extern/include" --include_path="C:/Program Files/MATLAB/R2021a/simulink/include" --include_path="C:/Program Files/MATLAB/R2021a/rtw/c/src" --include_path="C:/Program Files/MATLAB/R2021a/rtw/c/src/ext_mode/common" --include_path="C:/Program Files/MATLAB/R2021a/rtw/c/ert" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/target/supportpackages/tic2000/inc" --include_path="C:/Program Files/MATLAB/R2021a/toolbox/shared/can/src/scanutil" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/target/supportpackages/tic2000/src" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/shared/supportpackages/tic2000/src" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/shared/supportpackages/tic2000/inc" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/device_support/f28004x/common/include" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/libraries/calibration/hrpwm/f28004x/include" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/driverlib/f28004x/driverlib" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/driverlib/f28004x/driverlib/inc" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/device_support/f28004x/headers/include" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/device_support/f28004x/common" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/target/shared/externalmode_daemon/include" --include_path="C:/Program Files/MATLAB/R2021a/toolbox/rtw/targets/common/can/blocks/tlc_c" --define=MODEL=RealTimeMachine --define=NUMST=1 --define=NCSTATES=0 --define=HAVESTDIO --define=MODEL_HAS_DYNAMICALLY_LOADED_SFCNS=0 --define=CLASSIC_INTERFACE=0 --define=ALLOCATIONFCN=0 --define=TID01EQ=0 --define=TERMFCN=1 --define=ONESTEPFCN=1 --define=MAT_FILE=0 --define=MULTI_INSTANCE_CODE=0 --define=INTEGER_CODE=0 --define=MT=0 --define=DAEMON_MODE=1 --define=XCP_CUSTOM_PLATFORM --define=EXTMODE_DISABLE_ARGS_PROCESSING=1 --define=MW_PIL_SCIFIFOLEN=16 --define=CPU1 --define=F2837X_REG_FORMAT --define=MW_F28004X --define=STACK_SIZE=1024 --define=__MW_TARGET_USE_HARDWARE_RESOURCES_H__ --define=RT --define=F280049C --define=BOOT_FROM_FLASH=1 --abi=coffabi -s -v28 -ml --abi=coffabi  --preproc_dependency=$(@:%.obj=%.dep) --preproc_with_compile  --large_memory_model -I$(F28_HEADERS)/include -I$(TI_INCLUDE) -v28 --float_support=fpu32 -ml -DF280049C -DBOOT_FROM_FLASH=1 --tmu_support=tmu0 --fp_mode=relaxed --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

c28004xBoard_Realtime_Support.obj: C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/target/supportpackages/tic2000/src/c28004xBoard_Realtime_Support.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccs1040/ccs/tools/compiler/ti-cgt-c2000_20.2.5.LTS/bin/cl2000" --include_path="C:/ti/ccs1040/ccs/tools/compiler/ti-cgt-c2000_20.2.5.LTS/include" --include_path="E:/Documents/OneDrive - bwedu/Uni/Master/Semester 1 - 2021/Machatronisches Projekt/Matlab" --include_path="E:/Documents/OneDrive - bwedu/Uni/Master/Semester 1 - 2021/Machatronisches Projekt/Matlab/RealTimeMachine_ert_rtw" --include_path="C:/Program Files/MATLAB/R2021a/extern/include" --include_path="C:/Program Files/MATLAB/R2021a/simulink/include" --include_path="C:/Program Files/MATLAB/R2021a/rtw/c/src" --include_path="C:/Program Files/MATLAB/R2021a/rtw/c/src/ext_mode/common" --include_path="C:/Program Files/MATLAB/R2021a/rtw/c/ert" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/target/supportpackages/tic2000/inc" --include_path="C:/Program Files/MATLAB/R2021a/toolbox/shared/can/src/scanutil" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/target/supportpackages/tic2000/src" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/shared/supportpackages/tic2000/src" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/shared/supportpackages/tic2000/inc" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/device_support/f28004x/common/include" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/libraries/calibration/hrpwm/f28004x/include" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/driverlib/f28004x/driverlib" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/driverlib/f28004x/driverlib/inc" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/device_support/f28004x/headers/include" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/device_support/f28004x/common" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/target/shared/externalmode_daemon/include" --include_path="C:/Program Files/MATLAB/R2021a/toolbox/rtw/targets/common/can/blocks/tlc_c" --define=MODEL=RealTimeMachine --define=NUMST=1 --define=NCSTATES=0 --define=HAVESTDIO --define=MODEL_HAS_DYNAMICALLY_LOADED_SFCNS=0 --define=CLASSIC_INTERFACE=0 --define=ALLOCATIONFCN=0 --define=TID01EQ=0 --define=TERMFCN=1 --define=ONESTEPFCN=1 --define=MAT_FILE=0 --define=MULTI_INSTANCE_CODE=0 --define=INTEGER_CODE=0 --define=MT=0 --define=DAEMON_MODE=1 --define=XCP_CUSTOM_PLATFORM --define=EXTMODE_DISABLE_ARGS_PROCESSING=1 --define=MW_PIL_SCIFIFOLEN=16 --define=CPU1 --define=F2837X_REG_FORMAT --define=MW_F28004X --define=STACK_SIZE=1024 --define=__MW_TARGET_USE_HARDWARE_RESOURCES_H__ --define=RT --define=F280049C --define=BOOT_FROM_FLASH=1 --abi=coffabi -s -v28 -ml --abi=coffabi  --preproc_dependency=$(@:%.obj=%.dep) --preproc_with_compile  --large_memory_model -I$(F28_HEADERS)/include -I$(TI_INCLUDE) -v28 --float_support=fpu32 -ml -DF280049C -DBOOT_FROM_FLASH=1 --tmu_support=tmu0 --fp_mode=relaxed --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

c28004xSchedulerTimer0.obj: C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/target/supportpackages/tic2000/src/c28004xSchedulerTimer0.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccs1040/ccs/tools/compiler/ti-cgt-c2000_20.2.5.LTS/bin/cl2000" --include_path="C:/ti/ccs1040/ccs/tools/compiler/ti-cgt-c2000_20.2.5.LTS/include" --include_path="E:/Documents/OneDrive - bwedu/Uni/Master/Semester 1 - 2021/Machatronisches Projekt/Matlab" --include_path="E:/Documents/OneDrive - bwedu/Uni/Master/Semester 1 - 2021/Machatronisches Projekt/Matlab/RealTimeMachine_ert_rtw" --include_path="C:/Program Files/MATLAB/R2021a/extern/include" --include_path="C:/Program Files/MATLAB/R2021a/simulink/include" --include_path="C:/Program Files/MATLAB/R2021a/rtw/c/src" --include_path="C:/Program Files/MATLAB/R2021a/rtw/c/src/ext_mode/common" --include_path="C:/Program Files/MATLAB/R2021a/rtw/c/ert" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/target/supportpackages/tic2000/inc" --include_path="C:/Program Files/MATLAB/R2021a/toolbox/shared/can/src/scanutil" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/target/supportpackages/tic2000/src" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/shared/supportpackages/tic2000/src" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/shared/supportpackages/tic2000/inc" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/device_support/f28004x/common/include" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/libraries/calibration/hrpwm/f28004x/include" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/driverlib/f28004x/driverlib" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/driverlib/f28004x/driverlib/inc" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/device_support/f28004x/headers/include" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/device_support/f28004x/common" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/target/shared/externalmode_daemon/include" --include_path="C:/Program Files/MATLAB/R2021a/toolbox/rtw/targets/common/can/blocks/tlc_c" --define=MODEL=RealTimeMachine --define=NUMST=1 --define=NCSTATES=0 --define=HAVESTDIO --define=MODEL_HAS_DYNAMICALLY_LOADED_SFCNS=0 --define=CLASSIC_INTERFACE=0 --define=ALLOCATIONFCN=0 --define=TID01EQ=0 --define=TERMFCN=1 --define=ONESTEPFCN=1 --define=MAT_FILE=0 --define=MULTI_INSTANCE_CODE=0 --define=INTEGER_CODE=0 --define=MT=0 --define=DAEMON_MODE=1 --define=XCP_CUSTOM_PLATFORM --define=EXTMODE_DISABLE_ARGS_PROCESSING=1 --define=MW_PIL_SCIFIFOLEN=16 --define=CPU1 --define=F2837X_REG_FORMAT --define=MW_F28004X --define=STACK_SIZE=1024 --define=__MW_TARGET_USE_HARDWARE_RESOURCES_H__ --define=RT --define=F280049C --define=BOOT_FROM_FLASH=1 --abi=coffabi -s -v28 -ml --abi=coffabi  --preproc_dependency=$(@:%.obj=%.dep) --preproc_with_compile  --large_memory_model -I$(F28_HEADERS)/include -I$(TI_INCLUDE) -v28 --float_support=fpu32 -ml -DF280049C -DBOOT_FROM_FLASH=1 --tmu_support=tmu0 --fp_mode=relaxed --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

dma.obj: C:/ti/c2000/C2000Ware_3_04_00_00/driverlib/f28004x/driverlib/dma.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccs1040/ccs/tools/compiler/ti-cgt-c2000_20.2.5.LTS/bin/cl2000" --include_path="C:/ti/ccs1040/ccs/tools/compiler/ti-cgt-c2000_20.2.5.LTS/include" --include_path="E:/Documents/OneDrive - bwedu/Uni/Master/Semester 1 - 2021/Machatronisches Projekt/Matlab" --include_path="E:/Documents/OneDrive - bwedu/Uni/Master/Semester 1 - 2021/Machatronisches Projekt/Matlab/RealTimeMachine_ert_rtw" --include_path="C:/Program Files/MATLAB/R2021a/extern/include" --include_path="C:/Program Files/MATLAB/R2021a/simulink/include" --include_path="C:/Program Files/MATLAB/R2021a/rtw/c/src" --include_path="C:/Program Files/MATLAB/R2021a/rtw/c/src/ext_mode/common" --include_path="C:/Program Files/MATLAB/R2021a/rtw/c/ert" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/target/supportpackages/tic2000/inc" --include_path="C:/Program Files/MATLAB/R2021a/toolbox/shared/can/src/scanutil" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/target/supportpackages/tic2000/src" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/shared/supportpackages/tic2000/src" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/shared/supportpackages/tic2000/inc" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/device_support/f28004x/common/include" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/libraries/calibration/hrpwm/f28004x/include" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/driverlib/f28004x/driverlib" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/driverlib/f28004x/driverlib/inc" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/device_support/f28004x/headers/include" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/device_support/f28004x/common" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/target/shared/externalmode_daemon/include" --include_path="C:/Program Files/MATLAB/R2021a/toolbox/rtw/targets/common/can/blocks/tlc_c" --define=MODEL=RealTimeMachine --define=NUMST=1 --define=NCSTATES=0 --define=HAVESTDIO --define=MODEL_HAS_DYNAMICALLY_LOADED_SFCNS=0 --define=CLASSIC_INTERFACE=0 --define=ALLOCATIONFCN=0 --define=TID01EQ=0 --define=TERMFCN=1 --define=ONESTEPFCN=1 --define=MAT_FILE=0 --define=MULTI_INSTANCE_CODE=0 --define=INTEGER_CODE=0 --define=MT=0 --define=DAEMON_MODE=1 --define=XCP_CUSTOM_PLATFORM --define=EXTMODE_DISABLE_ARGS_PROCESSING=1 --define=MW_PIL_SCIFIFOLEN=16 --define=CPU1 --define=F2837X_REG_FORMAT --define=MW_F28004X --define=STACK_SIZE=1024 --define=__MW_TARGET_USE_HARDWARE_RESOURCES_H__ --define=RT --define=F280049C --define=BOOT_FROM_FLASH=1 --abi=coffabi -s -v28 -ml --abi=coffabi  --preproc_dependency=$(@:%.obj=%.dep) --preproc_with_compile  --large_memory_model -I$(F28_HEADERS)/include -I$(TI_INCLUDE) -v28 --float_support=fpu32 -ml -DF280049C -DBOOT_FROM_FLASH=1 --tmu_support=tmu0 --fp_mode=relaxed --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

ert_main.obj: E:/Documents/OneDrive\ -\ bwedu/Uni/Master/Semester\ 1\ -\ 2021/Machatronisches\ Projekt/Matlab/RealTimeMachine_ert_rtw/ert_main.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccs1040/ccs/tools/compiler/ti-cgt-c2000_20.2.5.LTS/bin/cl2000" --include_path="C:/ti/ccs1040/ccs/tools/compiler/ti-cgt-c2000_20.2.5.LTS/include" --include_path="E:/Documents/OneDrive - bwedu/Uni/Master/Semester 1 - 2021/Machatronisches Projekt/Matlab" --include_path="E:/Documents/OneDrive - bwedu/Uni/Master/Semester 1 - 2021/Machatronisches Projekt/Matlab/RealTimeMachine_ert_rtw" --include_path="C:/Program Files/MATLAB/R2021a/extern/include" --include_path="C:/Program Files/MATLAB/R2021a/simulink/include" --include_path="C:/Program Files/MATLAB/R2021a/rtw/c/src" --include_path="C:/Program Files/MATLAB/R2021a/rtw/c/src/ext_mode/common" --include_path="C:/Program Files/MATLAB/R2021a/rtw/c/ert" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/target/supportpackages/tic2000/inc" --include_path="C:/Program Files/MATLAB/R2021a/toolbox/shared/can/src/scanutil" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/target/supportpackages/tic2000/src" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/shared/supportpackages/tic2000/src" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/shared/supportpackages/tic2000/inc" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/device_support/f28004x/common/include" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/libraries/calibration/hrpwm/f28004x/include" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/driverlib/f28004x/driverlib" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/driverlib/f28004x/driverlib/inc" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/device_support/f28004x/headers/include" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/device_support/f28004x/common" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/target/shared/externalmode_daemon/include" --include_path="C:/Program Files/MATLAB/R2021a/toolbox/rtw/targets/common/can/blocks/tlc_c" --define=MODEL=RealTimeMachine --define=NUMST=1 --define=NCSTATES=0 --define=HAVESTDIO --define=MODEL_HAS_DYNAMICALLY_LOADED_SFCNS=0 --define=CLASSIC_INTERFACE=0 --define=ALLOCATIONFCN=0 --define=TID01EQ=0 --define=TERMFCN=1 --define=ONESTEPFCN=1 --define=MAT_FILE=0 --define=MULTI_INSTANCE_CODE=0 --define=INTEGER_CODE=0 --define=MT=0 --define=DAEMON_MODE=1 --define=XCP_CUSTOM_PLATFORM --define=EXTMODE_DISABLE_ARGS_PROCESSING=1 --define=MW_PIL_SCIFIFOLEN=16 --define=CPU1 --define=F2837X_REG_FORMAT --define=MW_F28004X --define=STACK_SIZE=1024 --define=__MW_TARGET_USE_HARDWARE_RESOURCES_H__ --define=RT --define=F280049C --define=BOOT_FROM_FLASH=1 --abi=coffabi -s -v28 -ml --abi=coffabi  --preproc_dependency=$(@:%.obj=%.dep) --preproc_with_compile  --large_memory_model -I$(F28_HEADERS)/include -I$(TI_INCLUDE) -v28 --float_support=fpu32 -ml -DF280049C -DBOOT_FROM_FLASH=1 --tmu_support=tmu0 --fp_mode=relaxed --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

f28004x_adc.obj: C:/ti/c2000/C2000Ware_3_04_00_00/device_support/f28004x/common/source/f28004x_adc.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccs1040/ccs/tools/compiler/ti-cgt-c2000_20.2.5.LTS/bin/cl2000" --include_path="C:/ti/ccs1040/ccs/tools/compiler/ti-cgt-c2000_20.2.5.LTS/include" --include_path="E:/Documents/OneDrive - bwedu/Uni/Master/Semester 1 - 2021/Machatronisches Projekt/Matlab" --include_path="E:/Documents/OneDrive - bwedu/Uni/Master/Semester 1 - 2021/Machatronisches Projekt/Matlab/RealTimeMachine_ert_rtw" --include_path="C:/Program Files/MATLAB/R2021a/extern/include" --include_path="C:/Program Files/MATLAB/R2021a/simulink/include" --include_path="C:/Program Files/MATLAB/R2021a/rtw/c/src" --include_path="C:/Program Files/MATLAB/R2021a/rtw/c/src/ext_mode/common" --include_path="C:/Program Files/MATLAB/R2021a/rtw/c/ert" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/target/supportpackages/tic2000/inc" --include_path="C:/Program Files/MATLAB/R2021a/toolbox/shared/can/src/scanutil" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/target/supportpackages/tic2000/src" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/shared/supportpackages/tic2000/src" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/shared/supportpackages/tic2000/inc" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/device_support/f28004x/common/include" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/libraries/calibration/hrpwm/f28004x/include" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/driverlib/f28004x/driverlib" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/driverlib/f28004x/driverlib/inc" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/device_support/f28004x/headers/include" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/device_support/f28004x/common" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/target/shared/externalmode_daemon/include" --include_path="C:/Program Files/MATLAB/R2021a/toolbox/rtw/targets/common/can/blocks/tlc_c" --define=MODEL=RealTimeMachine --define=NUMST=1 --define=NCSTATES=0 --define=HAVESTDIO --define=MODEL_HAS_DYNAMICALLY_LOADED_SFCNS=0 --define=CLASSIC_INTERFACE=0 --define=ALLOCATIONFCN=0 --define=TID01EQ=0 --define=TERMFCN=1 --define=ONESTEPFCN=1 --define=MAT_FILE=0 --define=MULTI_INSTANCE_CODE=0 --define=INTEGER_CODE=0 --define=MT=0 --define=DAEMON_MODE=1 --define=XCP_CUSTOM_PLATFORM --define=EXTMODE_DISABLE_ARGS_PROCESSING=1 --define=MW_PIL_SCIFIFOLEN=16 --define=CPU1 --define=F2837X_REG_FORMAT --define=MW_F28004X --define=STACK_SIZE=1024 --define=__MW_TARGET_USE_HARDWARE_RESOURCES_H__ --define=RT --define=F280049C --define=BOOT_FROM_FLASH=1 --abi=coffabi -s -v28 -ml --abi=coffabi  --preproc_dependency=$(@:%.obj=%.dep) --preproc_with_compile  --large_memory_model -I$(F28_HEADERS)/include -I$(TI_INCLUDE) -v28 --float_support=fpu32 -ml -DF280049C -DBOOT_FROM_FLASH=1 --tmu_support=tmu0 --fp_mode=relaxed --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

f28004x_codestartbranch.obj: C:/ti/c2000/C2000Ware_3_04_00_00/device_support/f28004x/common/source/f28004x_codestartbranch.asm $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccs1040/ccs/tools/compiler/ti-cgt-c2000_20.2.5.LTS/bin/cl2000" --include_path="C:/ti/ccs1040/ccs/tools/compiler/ti-cgt-c2000_20.2.5.LTS/include" --include_path="E:/Documents/OneDrive - bwedu/Uni/Master/Semester 1 - 2021/Machatronisches Projekt/Matlab" --include_path="E:/Documents/OneDrive - bwedu/Uni/Master/Semester 1 - 2021/Machatronisches Projekt/Matlab/RealTimeMachine_ert_rtw" --include_path="C:/Program Files/MATLAB/R2021a/extern/include" --include_path="C:/Program Files/MATLAB/R2021a/simulink/include" --include_path="C:/Program Files/MATLAB/R2021a/rtw/c/src" --include_path="C:/Program Files/MATLAB/R2021a/rtw/c/src/ext_mode/common" --include_path="C:/Program Files/MATLAB/R2021a/rtw/c/ert" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/target/supportpackages/tic2000/inc" --include_path="C:/Program Files/MATLAB/R2021a/toolbox/shared/can/src/scanutil" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/target/supportpackages/tic2000/src" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/shared/supportpackages/tic2000/src" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/shared/supportpackages/tic2000/inc" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/device_support/f28004x/common/include" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/libraries/calibration/hrpwm/f28004x/include" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/driverlib/f28004x/driverlib" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/driverlib/f28004x/driverlib/inc" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/device_support/f28004x/headers/include" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/device_support/f28004x/common" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/target/shared/externalmode_daemon/include" --include_path="C:/Program Files/MATLAB/R2021a/toolbox/rtw/targets/common/can/blocks/tlc_c" --define=MODEL=RealTimeMachine --define=NUMST=1 --define=NCSTATES=0 --define=HAVESTDIO --define=MODEL_HAS_DYNAMICALLY_LOADED_SFCNS=0 --define=CLASSIC_INTERFACE=0 --define=ALLOCATIONFCN=0 --define=TID01EQ=0 --define=TERMFCN=1 --define=ONESTEPFCN=1 --define=MAT_FILE=0 --define=MULTI_INSTANCE_CODE=0 --define=INTEGER_CODE=0 --define=MT=0 --define=DAEMON_MODE=1 --define=XCP_CUSTOM_PLATFORM --define=EXTMODE_DISABLE_ARGS_PROCESSING=1 --define=MW_PIL_SCIFIFOLEN=16 --define=CPU1 --define=F2837X_REG_FORMAT --define=MW_F28004X --define=STACK_SIZE=1024 --define=__MW_TARGET_USE_HARDWARE_RESOURCES_H__ --define=RT --define=F280049C --define=BOOT_FROM_FLASH=1 --abi=coffabi -s -v28 -ml --abi=coffabi  --preproc_dependency=$(@:%.obj=%.dep) --preproc_with_compile  --large_memory_model -I$(F28_HEADERS)/include -I$(TI_INCLUDE) -v28 --float_support=fpu32 -ml -DF280049C -DBOOT_FROM_FLASH=1 --tmu_support=tmu0 --fp_mode=relaxed --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

f28004x_cputimers.obj: C:/ti/c2000/C2000Ware_3_04_00_00/device_support/f28004x/common/source/f28004x_cputimers.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccs1040/ccs/tools/compiler/ti-cgt-c2000_20.2.5.LTS/bin/cl2000" --include_path="C:/ti/ccs1040/ccs/tools/compiler/ti-cgt-c2000_20.2.5.LTS/include" --include_path="E:/Documents/OneDrive - bwedu/Uni/Master/Semester 1 - 2021/Machatronisches Projekt/Matlab" --include_path="E:/Documents/OneDrive - bwedu/Uni/Master/Semester 1 - 2021/Machatronisches Projekt/Matlab/RealTimeMachine_ert_rtw" --include_path="C:/Program Files/MATLAB/R2021a/extern/include" --include_path="C:/Program Files/MATLAB/R2021a/simulink/include" --include_path="C:/Program Files/MATLAB/R2021a/rtw/c/src" --include_path="C:/Program Files/MATLAB/R2021a/rtw/c/src/ext_mode/common" --include_path="C:/Program Files/MATLAB/R2021a/rtw/c/ert" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/target/supportpackages/tic2000/inc" --include_path="C:/Program Files/MATLAB/R2021a/toolbox/shared/can/src/scanutil" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/target/supportpackages/tic2000/src" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/shared/supportpackages/tic2000/src" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/shared/supportpackages/tic2000/inc" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/device_support/f28004x/common/include" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/libraries/calibration/hrpwm/f28004x/include" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/driverlib/f28004x/driverlib" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/driverlib/f28004x/driverlib/inc" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/device_support/f28004x/headers/include" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/device_support/f28004x/common" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/target/shared/externalmode_daemon/include" --include_path="C:/Program Files/MATLAB/R2021a/toolbox/rtw/targets/common/can/blocks/tlc_c" --define=MODEL=RealTimeMachine --define=NUMST=1 --define=NCSTATES=0 --define=HAVESTDIO --define=MODEL_HAS_DYNAMICALLY_LOADED_SFCNS=0 --define=CLASSIC_INTERFACE=0 --define=ALLOCATIONFCN=0 --define=TID01EQ=0 --define=TERMFCN=1 --define=ONESTEPFCN=1 --define=MAT_FILE=0 --define=MULTI_INSTANCE_CODE=0 --define=INTEGER_CODE=0 --define=MT=0 --define=DAEMON_MODE=1 --define=XCP_CUSTOM_PLATFORM --define=EXTMODE_DISABLE_ARGS_PROCESSING=1 --define=MW_PIL_SCIFIFOLEN=16 --define=CPU1 --define=F2837X_REG_FORMAT --define=MW_F28004X --define=STACK_SIZE=1024 --define=__MW_TARGET_USE_HARDWARE_RESOURCES_H__ --define=RT --define=F280049C --define=BOOT_FROM_FLASH=1 --abi=coffabi -s -v28 -ml --abi=coffabi  --preproc_dependency=$(@:%.obj=%.dep) --preproc_with_compile  --large_memory_model -I$(F28_HEADERS)/include -I$(TI_INCLUDE) -v28 --float_support=fpu32 -ml -DF280049C -DBOOT_FROM_FLASH=1 --tmu_support=tmu0 --fp_mode=relaxed --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

f28004x_defaultisr.obj: C:/ti/c2000/C2000Ware_3_04_00_00/device_support/f28004x/common/source/f28004x_defaultisr.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccs1040/ccs/tools/compiler/ti-cgt-c2000_20.2.5.LTS/bin/cl2000" --include_path="C:/ti/ccs1040/ccs/tools/compiler/ti-cgt-c2000_20.2.5.LTS/include" --include_path="E:/Documents/OneDrive - bwedu/Uni/Master/Semester 1 - 2021/Machatronisches Projekt/Matlab" --include_path="E:/Documents/OneDrive - bwedu/Uni/Master/Semester 1 - 2021/Machatronisches Projekt/Matlab/RealTimeMachine_ert_rtw" --include_path="C:/Program Files/MATLAB/R2021a/extern/include" --include_path="C:/Program Files/MATLAB/R2021a/simulink/include" --include_path="C:/Program Files/MATLAB/R2021a/rtw/c/src" --include_path="C:/Program Files/MATLAB/R2021a/rtw/c/src/ext_mode/common" --include_path="C:/Program Files/MATLAB/R2021a/rtw/c/ert" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/target/supportpackages/tic2000/inc" --include_path="C:/Program Files/MATLAB/R2021a/toolbox/shared/can/src/scanutil" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/target/supportpackages/tic2000/src" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/shared/supportpackages/tic2000/src" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/shared/supportpackages/tic2000/inc" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/device_support/f28004x/common/include" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/libraries/calibration/hrpwm/f28004x/include" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/driverlib/f28004x/driverlib" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/driverlib/f28004x/driverlib/inc" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/device_support/f28004x/headers/include" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/device_support/f28004x/common" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/target/shared/externalmode_daemon/include" --include_path="C:/Program Files/MATLAB/R2021a/toolbox/rtw/targets/common/can/blocks/tlc_c" --define=MODEL=RealTimeMachine --define=NUMST=1 --define=NCSTATES=0 --define=HAVESTDIO --define=MODEL_HAS_DYNAMICALLY_LOADED_SFCNS=0 --define=CLASSIC_INTERFACE=0 --define=ALLOCATIONFCN=0 --define=TID01EQ=0 --define=TERMFCN=1 --define=ONESTEPFCN=1 --define=MAT_FILE=0 --define=MULTI_INSTANCE_CODE=0 --define=INTEGER_CODE=0 --define=MT=0 --define=DAEMON_MODE=1 --define=XCP_CUSTOM_PLATFORM --define=EXTMODE_DISABLE_ARGS_PROCESSING=1 --define=MW_PIL_SCIFIFOLEN=16 --define=CPU1 --define=F2837X_REG_FORMAT --define=MW_F28004X --define=STACK_SIZE=1024 --define=__MW_TARGET_USE_HARDWARE_RESOURCES_H__ --define=RT --define=F280049C --define=BOOT_FROM_FLASH=1 --abi=coffabi -s -v28 -ml --abi=coffabi  --preproc_dependency=$(@:%.obj=%.dep) --preproc_with_compile  --large_memory_model -I$(F28_HEADERS)/include -I$(TI_INCLUDE) -v28 --float_support=fpu32 -ml -DF280049C -DBOOT_FROM_FLASH=1 --tmu_support=tmu0 --fp_mode=relaxed --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

f28004x_globalvariabledefs.obj: C:/ti/c2000/C2000Ware_3_04_00_00/device_support/f28004x/headers/source/f28004x_globalvariabledefs.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccs1040/ccs/tools/compiler/ti-cgt-c2000_20.2.5.LTS/bin/cl2000" --include_path="C:/ti/ccs1040/ccs/tools/compiler/ti-cgt-c2000_20.2.5.LTS/include" --include_path="E:/Documents/OneDrive - bwedu/Uni/Master/Semester 1 - 2021/Machatronisches Projekt/Matlab" --include_path="E:/Documents/OneDrive - bwedu/Uni/Master/Semester 1 - 2021/Machatronisches Projekt/Matlab/RealTimeMachine_ert_rtw" --include_path="C:/Program Files/MATLAB/R2021a/extern/include" --include_path="C:/Program Files/MATLAB/R2021a/simulink/include" --include_path="C:/Program Files/MATLAB/R2021a/rtw/c/src" --include_path="C:/Program Files/MATLAB/R2021a/rtw/c/src/ext_mode/common" --include_path="C:/Program Files/MATLAB/R2021a/rtw/c/ert" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/target/supportpackages/tic2000/inc" --include_path="C:/Program Files/MATLAB/R2021a/toolbox/shared/can/src/scanutil" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/target/supportpackages/tic2000/src" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/shared/supportpackages/tic2000/src" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/shared/supportpackages/tic2000/inc" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/device_support/f28004x/common/include" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/libraries/calibration/hrpwm/f28004x/include" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/driverlib/f28004x/driverlib" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/driverlib/f28004x/driverlib/inc" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/device_support/f28004x/headers/include" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/device_support/f28004x/common" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/target/shared/externalmode_daemon/include" --include_path="C:/Program Files/MATLAB/R2021a/toolbox/rtw/targets/common/can/blocks/tlc_c" --define=MODEL=RealTimeMachine --define=NUMST=1 --define=NCSTATES=0 --define=HAVESTDIO --define=MODEL_HAS_DYNAMICALLY_LOADED_SFCNS=0 --define=CLASSIC_INTERFACE=0 --define=ALLOCATIONFCN=0 --define=TID01EQ=0 --define=TERMFCN=1 --define=ONESTEPFCN=1 --define=MAT_FILE=0 --define=MULTI_INSTANCE_CODE=0 --define=INTEGER_CODE=0 --define=MT=0 --define=DAEMON_MODE=1 --define=XCP_CUSTOM_PLATFORM --define=EXTMODE_DISABLE_ARGS_PROCESSING=1 --define=MW_PIL_SCIFIFOLEN=16 --define=CPU1 --define=F2837X_REG_FORMAT --define=MW_F28004X --define=STACK_SIZE=1024 --define=__MW_TARGET_USE_HARDWARE_RESOURCES_H__ --define=RT --define=F280049C --define=BOOT_FROM_FLASH=1 --abi=coffabi -s -v28 -ml --abi=coffabi  --preproc_dependency=$(@:%.obj=%.dep) --preproc_with_compile  --large_memory_model -I$(F28_HEADERS)/include -I$(TI_INCLUDE) -v28 --float_support=fpu32 -ml -DF280049C -DBOOT_FROM_FLASH=1 --tmu_support=tmu0 --fp_mode=relaxed --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

f28004x_gpio.obj: C:/ti/c2000/C2000Ware_3_04_00_00/device_support/f28004x/common/source/f28004x_gpio.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccs1040/ccs/tools/compiler/ti-cgt-c2000_20.2.5.LTS/bin/cl2000" --include_path="C:/ti/ccs1040/ccs/tools/compiler/ti-cgt-c2000_20.2.5.LTS/include" --include_path="E:/Documents/OneDrive - bwedu/Uni/Master/Semester 1 - 2021/Machatronisches Projekt/Matlab" --include_path="E:/Documents/OneDrive - bwedu/Uni/Master/Semester 1 - 2021/Machatronisches Projekt/Matlab/RealTimeMachine_ert_rtw" --include_path="C:/Program Files/MATLAB/R2021a/extern/include" --include_path="C:/Program Files/MATLAB/R2021a/simulink/include" --include_path="C:/Program Files/MATLAB/R2021a/rtw/c/src" --include_path="C:/Program Files/MATLAB/R2021a/rtw/c/src/ext_mode/common" --include_path="C:/Program Files/MATLAB/R2021a/rtw/c/ert" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/target/supportpackages/tic2000/inc" --include_path="C:/Program Files/MATLAB/R2021a/toolbox/shared/can/src/scanutil" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/target/supportpackages/tic2000/src" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/shared/supportpackages/tic2000/src" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/shared/supportpackages/tic2000/inc" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/device_support/f28004x/common/include" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/libraries/calibration/hrpwm/f28004x/include" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/driverlib/f28004x/driverlib" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/driverlib/f28004x/driverlib/inc" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/device_support/f28004x/headers/include" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/device_support/f28004x/common" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/target/shared/externalmode_daemon/include" --include_path="C:/Program Files/MATLAB/R2021a/toolbox/rtw/targets/common/can/blocks/tlc_c" --define=MODEL=RealTimeMachine --define=NUMST=1 --define=NCSTATES=0 --define=HAVESTDIO --define=MODEL_HAS_DYNAMICALLY_LOADED_SFCNS=0 --define=CLASSIC_INTERFACE=0 --define=ALLOCATIONFCN=0 --define=TID01EQ=0 --define=TERMFCN=1 --define=ONESTEPFCN=1 --define=MAT_FILE=0 --define=MULTI_INSTANCE_CODE=0 --define=INTEGER_CODE=0 --define=MT=0 --define=DAEMON_MODE=1 --define=XCP_CUSTOM_PLATFORM --define=EXTMODE_DISABLE_ARGS_PROCESSING=1 --define=MW_PIL_SCIFIFOLEN=16 --define=CPU1 --define=F2837X_REG_FORMAT --define=MW_F28004X --define=STACK_SIZE=1024 --define=__MW_TARGET_USE_HARDWARE_RESOURCES_H__ --define=RT --define=F280049C --define=BOOT_FROM_FLASH=1 --abi=coffabi -s -v28 -ml --abi=coffabi  --preproc_dependency=$(@:%.obj=%.dep) --preproc_with_compile  --large_memory_model -I$(F28_HEADERS)/include -I$(TI_INCLUDE) -v28 --float_support=fpu32 -ml -DF280049C -DBOOT_FROM_FLASH=1 --tmu_support=tmu0 --fp_mode=relaxed --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

f28004x_piectrl.obj: C:/ti/c2000/C2000Ware_3_04_00_00/device_support/f28004x/common/source/f28004x_piectrl.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccs1040/ccs/tools/compiler/ti-cgt-c2000_20.2.5.LTS/bin/cl2000" --include_path="C:/ti/ccs1040/ccs/tools/compiler/ti-cgt-c2000_20.2.5.LTS/include" --include_path="E:/Documents/OneDrive - bwedu/Uni/Master/Semester 1 - 2021/Machatronisches Projekt/Matlab" --include_path="E:/Documents/OneDrive - bwedu/Uni/Master/Semester 1 - 2021/Machatronisches Projekt/Matlab/RealTimeMachine_ert_rtw" --include_path="C:/Program Files/MATLAB/R2021a/extern/include" --include_path="C:/Program Files/MATLAB/R2021a/simulink/include" --include_path="C:/Program Files/MATLAB/R2021a/rtw/c/src" --include_path="C:/Program Files/MATLAB/R2021a/rtw/c/src/ext_mode/common" --include_path="C:/Program Files/MATLAB/R2021a/rtw/c/ert" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/target/supportpackages/tic2000/inc" --include_path="C:/Program Files/MATLAB/R2021a/toolbox/shared/can/src/scanutil" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/target/supportpackages/tic2000/src" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/shared/supportpackages/tic2000/src" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/shared/supportpackages/tic2000/inc" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/device_support/f28004x/common/include" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/libraries/calibration/hrpwm/f28004x/include" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/driverlib/f28004x/driverlib" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/driverlib/f28004x/driverlib/inc" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/device_support/f28004x/headers/include" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/device_support/f28004x/common" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/target/shared/externalmode_daemon/include" --include_path="C:/Program Files/MATLAB/R2021a/toolbox/rtw/targets/common/can/blocks/tlc_c" --define=MODEL=RealTimeMachine --define=NUMST=1 --define=NCSTATES=0 --define=HAVESTDIO --define=MODEL_HAS_DYNAMICALLY_LOADED_SFCNS=0 --define=CLASSIC_INTERFACE=0 --define=ALLOCATIONFCN=0 --define=TID01EQ=0 --define=TERMFCN=1 --define=ONESTEPFCN=1 --define=MAT_FILE=0 --define=MULTI_INSTANCE_CODE=0 --define=INTEGER_CODE=0 --define=MT=0 --define=DAEMON_MODE=1 --define=XCP_CUSTOM_PLATFORM --define=EXTMODE_DISABLE_ARGS_PROCESSING=1 --define=MW_PIL_SCIFIFOLEN=16 --define=CPU1 --define=F2837X_REG_FORMAT --define=MW_F28004X --define=STACK_SIZE=1024 --define=__MW_TARGET_USE_HARDWARE_RESOURCES_H__ --define=RT --define=F280049C --define=BOOT_FROM_FLASH=1 --abi=coffabi -s -v28 -ml --abi=coffabi  --preproc_dependency=$(@:%.obj=%.dep) --preproc_with_compile  --large_memory_model -I$(F28_HEADERS)/include -I$(TI_INCLUDE) -v28 --float_support=fpu32 -ml -DF280049C -DBOOT_FROM_FLASH=1 --tmu_support=tmu0 --fp_mode=relaxed --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

f28004x_pievect.obj: C:/ti/c2000/C2000Ware_3_04_00_00/device_support/f28004x/common/source/f28004x_pievect.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccs1040/ccs/tools/compiler/ti-cgt-c2000_20.2.5.LTS/bin/cl2000" --include_path="C:/ti/ccs1040/ccs/tools/compiler/ti-cgt-c2000_20.2.5.LTS/include" --include_path="E:/Documents/OneDrive - bwedu/Uni/Master/Semester 1 - 2021/Machatronisches Projekt/Matlab" --include_path="E:/Documents/OneDrive - bwedu/Uni/Master/Semester 1 - 2021/Machatronisches Projekt/Matlab/RealTimeMachine_ert_rtw" --include_path="C:/Program Files/MATLAB/R2021a/extern/include" --include_path="C:/Program Files/MATLAB/R2021a/simulink/include" --include_path="C:/Program Files/MATLAB/R2021a/rtw/c/src" --include_path="C:/Program Files/MATLAB/R2021a/rtw/c/src/ext_mode/common" --include_path="C:/Program Files/MATLAB/R2021a/rtw/c/ert" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/target/supportpackages/tic2000/inc" --include_path="C:/Program Files/MATLAB/R2021a/toolbox/shared/can/src/scanutil" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/target/supportpackages/tic2000/src" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/shared/supportpackages/tic2000/src" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/shared/supportpackages/tic2000/inc" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/device_support/f28004x/common/include" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/libraries/calibration/hrpwm/f28004x/include" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/driverlib/f28004x/driverlib" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/driverlib/f28004x/driverlib/inc" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/device_support/f28004x/headers/include" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/device_support/f28004x/common" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/target/shared/externalmode_daemon/include" --include_path="C:/Program Files/MATLAB/R2021a/toolbox/rtw/targets/common/can/blocks/tlc_c" --define=MODEL=RealTimeMachine --define=NUMST=1 --define=NCSTATES=0 --define=HAVESTDIO --define=MODEL_HAS_DYNAMICALLY_LOADED_SFCNS=0 --define=CLASSIC_INTERFACE=0 --define=ALLOCATIONFCN=0 --define=TID01EQ=0 --define=TERMFCN=1 --define=ONESTEPFCN=1 --define=MAT_FILE=0 --define=MULTI_INSTANCE_CODE=0 --define=INTEGER_CODE=0 --define=MT=0 --define=DAEMON_MODE=1 --define=XCP_CUSTOM_PLATFORM --define=EXTMODE_DISABLE_ARGS_PROCESSING=1 --define=MW_PIL_SCIFIFOLEN=16 --define=CPU1 --define=F2837X_REG_FORMAT --define=MW_F28004X --define=STACK_SIZE=1024 --define=__MW_TARGET_USE_HARDWARE_RESOURCES_H__ --define=RT --define=F280049C --define=BOOT_FROM_FLASH=1 --abi=coffabi -s -v28 -ml --abi=coffabi  --preproc_dependency=$(@:%.obj=%.dep) --preproc_with_compile  --large_memory_model -I$(F28_HEADERS)/include -I$(TI_INCLUDE) -v28 --float_support=fpu32 -ml -DF280049C -DBOOT_FROM_FLASH=1 --tmu_support=tmu0 --fp_mode=relaxed --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

f28004x_sysctrl.obj: C:/ti/c2000/C2000Ware_3_04_00_00/device_support/f28004x/common/source/f28004x_sysctrl.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccs1040/ccs/tools/compiler/ti-cgt-c2000_20.2.5.LTS/bin/cl2000" --include_path="C:/ti/ccs1040/ccs/tools/compiler/ti-cgt-c2000_20.2.5.LTS/include" --include_path="E:/Documents/OneDrive - bwedu/Uni/Master/Semester 1 - 2021/Machatronisches Projekt/Matlab" --include_path="E:/Documents/OneDrive - bwedu/Uni/Master/Semester 1 - 2021/Machatronisches Projekt/Matlab/RealTimeMachine_ert_rtw" --include_path="C:/Program Files/MATLAB/R2021a/extern/include" --include_path="C:/Program Files/MATLAB/R2021a/simulink/include" --include_path="C:/Program Files/MATLAB/R2021a/rtw/c/src" --include_path="C:/Program Files/MATLAB/R2021a/rtw/c/src/ext_mode/common" --include_path="C:/Program Files/MATLAB/R2021a/rtw/c/ert" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/target/supportpackages/tic2000/inc" --include_path="C:/Program Files/MATLAB/R2021a/toolbox/shared/can/src/scanutil" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/target/supportpackages/tic2000/src" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/shared/supportpackages/tic2000/src" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/shared/supportpackages/tic2000/inc" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/device_support/f28004x/common/include" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/libraries/calibration/hrpwm/f28004x/include" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/driverlib/f28004x/driverlib" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/driverlib/f28004x/driverlib/inc" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/device_support/f28004x/headers/include" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/device_support/f28004x/common" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/target/shared/externalmode_daemon/include" --include_path="C:/Program Files/MATLAB/R2021a/toolbox/rtw/targets/common/can/blocks/tlc_c" --define=MODEL=RealTimeMachine --define=NUMST=1 --define=NCSTATES=0 --define=HAVESTDIO --define=MODEL_HAS_DYNAMICALLY_LOADED_SFCNS=0 --define=CLASSIC_INTERFACE=0 --define=ALLOCATIONFCN=0 --define=TID01EQ=0 --define=TERMFCN=1 --define=ONESTEPFCN=1 --define=MAT_FILE=0 --define=MULTI_INSTANCE_CODE=0 --define=INTEGER_CODE=0 --define=MT=0 --define=DAEMON_MODE=1 --define=XCP_CUSTOM_PLATFORM --define=EXTMODE_DISABLE_ARGS_PROCESSING=1 --define=MW_PIL_SCIFIFOLEN=16 --define=CPU1 --define=F2837X_REG_FORMAT --define=MW_F28004X --define=STACK_SIZE=1024 --define=__MW_TARGET_USE_HARDWARE_RESOURCES_H__ --define=RT --define=F280049C --define=BOOT_FROM_FLASH=1 --abi=coffabi -s -v28 -ml --abi=coffabi  --preproc_dependency=$(@:%.obj=%.dep) --preproc_with_compile  --large_memory_model -I$(F28_HEADERS)/include -I$(TI_INCLUDE) -v28 --float_support=fpu32 -ml -DF280049C -DBOOT_FROM_FLASH=1 --tmu_support=tmu0 --fp_mode=relaxed --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

f28004x_usdelay.obj: C:/ti/c2000/C2000Ware_3_04_00_00/device_support/f28004x/common/source/f28004x_usdelay.asm $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccs1040/ccs/tools/compiler/ti-cgt-c2000_20.2.5.LTS/bin/cl2000" --include_path="C:/ti/ccs1040/ccs/tools/compiler/ti-cgt-c2000_20.2.5.LTS/include" --include_path="E:/Documents/OneDrive - bwedu/Uni/Master/Semester 1 - 2021/Machatronisches Projekt/Matlab" --include_path="E:/Documents/OneDrive - bwedu/Uni/Master/Semester 1 - 2021/Machatronisches Projekt/Matlab/RealTimeMachine_ert_rtw" --include_path="C:/Program Files/MATLAB/R2021a/extern/include" --include_path="C:/Program Files/MATLAB/R2021a/simulink/include" --include_path="C:/Program Files/MATLAB/R2021a/rtw/c/src" --include_path="C:/Program Files/MATLAB/R2021a/rtw/c/src/ext_mode/common" --include_path="C:/Program Files/MATLAB/R2021a/rtw/c/ert" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/target/supportpackages/tic2000/inc" --include_path="C:/Program Files/MATLAB/R2021a/toolbox/shared/can/src/scanutil" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/target/supportpackages/tic2000/src" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/shared/supportpackages/tic2000/src" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/shared/supportpackages/tic2000/inc" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/device_support/f28004x/common/include" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/libraries/calibration/hrpwm/f28004x/include" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/driverlib/f28004x/driverlib" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/driverlib/f28004x/driverlib/inc" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/device_support/f28004x/headers/include" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/device_support/f28004x/common" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/target/shared/externalmode_daemon/include" --include_path="C:/Program Files/MATLAB/R2021a/toolbox/rtw/targets/common/can/blocks/tlc_c" --define=MODEL=RealTimeMachine --define=NUMST=1 --define=NCSTATES=0 --define=HAVESTDIO --define=MODEL_HAS_DYNAMICALLY_LOADED_SFCNS=0 --define=CLASSIC_INTERFACE=0 --define=ALLOCATIONFCN=0 --define=TID01EQ=0 --define=TERMFCN=1 --define=ONESTEPFCN=1 --define=MAT_FILE=0 --define=MULTI_INSTANCE_CODE=0 --define=INTEGER_CODE=0 --define=MT=0 --define=DAEMON_MODE=1 --define=XCP_CUSTOM_PLATFORM --define=EXTMODE_DISABLE_ARGS_PROCESSING=1 --define=MW_PIL_SCIFIFOLEN=16 --define=CPU1 --define=F2837X_REG_FORMAT --define=MW_F28004X --define=STACK_SIZE=1024 --define=__MW_TARGET_USE_HARDWARE_RESOURCES_H__ --define=RT --define=F280049C --define=BOOT_FROM_FLASH=1 --abi=coffabi -s -v28 -ml --abi=coffabi  --preproc_dependency=$(@:%.obj=%.dep) --preproc_with_compile  --large_memory_model -I$(F28_HEADERS)/include -I$(TI_INCLUDE) -v28 --float_support=fpu32 -ml -DF280049C -DBOOT_FROM_FLASH=1 --tmu_support=tmu0 --fp_mode=relaxed --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

profiler_Support.obj: C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/target/supportpackages/tic2000/src/profiler_Support.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccs1040/ccs/tools/compiler/ti-cgt-c2000_20.2.5.LTS/bin/cl2000" --include_path="C:/ti/ccs1040/ccs/tools/compiler/ti-cgt-c2000_20.2.5.LTS/include" --include_path="E:/Documents/OneDrive - bwedu/Uni/Master/Semester 1 - 2021/Machatronisches Projekt/Matlab" --include_path="E:/Documents/OneDrive - bwedu/Uni/Master/Semester 1 - 2021/Machatronisches Projekt/Matlab/RealTimeMachine_ert_rtw" --include_path="C:/Program Files/MATLAB/R2021a/extern/include" --include_path="C:/Program Files/MATLAB/R2021a/simulink/include" --include_path="C:/Program Files/MATLAB/R2021a/rtw/c/src" --include_path="C:/Program Files/MATLAB/R2021a/rtw/c/src/ext_mode/common" --include_path="C:/Program Files/MATLAB/R2021a/rtw/c/ert" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/target/supportpackages/tic2000/inc" --include_path="C:/Program Files/MATLAB/R2021a/toolbox/shared/can/src/scanutil" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/target/supportpackages/tic2000/src" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/shared/supportpackages/tic2000/src" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/shared/supportpackages/tic2000/inc" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/device_support/f28004x/common/include" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/libraries/calibration/hrpwm/f28004x/include" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/driverlib/f28004x/driverlib" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/driverlib/f28004x/driverlib/inc" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/device_support/f28004x/headers/include" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/device_support/f28004x/common" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/target/shared/externalmode_daemon/include" --include_path="C:/Program Files/MATLAB/R2021a/toolbox/rtw/targets/common/can/blocks/tlc_c" --define=MODEL=RealTimeMachine --define=NUMST=1 --define=NCSTATES=0 --define=HAVESTDIO --define=MODEL_HAS_DYNAMICALLY_LOADED_SFCNS=0 --define=CLASSIC_INTERFACE=0 --define=ALLOCATIONFCN=0 --define=TID01EQ=0 --define=TERMFCN=1 --define=ONESTEPFCN=1 --define=MAT_FILE=0 --define=MULTI_INSTANCE_CODE=0 --define=INTEGER_CODE=0 --define=MT=0 --define=DAEMON_MODE=1 --define=XCP_CUSTOM_PLATFORM --define=EXTMODE_DISABLE_ARGS_PROCESSING=1 --define=MW_PIL_SCIFIFOLEN=16 --define=CPU1 --define=F2837X_REG_FORMAT --define=MW_F28004X --define=STACK_SIZE=1024 --define=__MW_TARGET_USE_HARDWARE_RESOURCES_H__ --define=RT --define=F280049C --define=BOOT_FROM_FLASH=1 --abi=coffabi -s -v28 -ml --abi=coffabi  --preproc_dependency=$(@:%.obj=%.dep) --preproc_with_compile  --large_memory_model -I$(F28_HEADERS)/include -I$(TI_INCLUDE) -v28 --float_support=fpu32 -ml -DF280049C -DBOOT_FROM_FLASH=1 --tmu_support=tmu0 --fp_mode=relaxed --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

sysctl.obj: C:/ti/c2000/C2000Ware_3_04_00_00/driverlib/f28004x/driverlib/sysctl.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccs1040/ccs/tools/compiler/ti-cgt-c2000_20.2.5.LTS/bin/cl2000" --include_path="C:/ti/ccs1040/ccs/tools/compiler/ti-cgt-c2000_20.2.5.LTS/include" --include_path="E:/Documents/OneDrive - bwedu/Uni/Master/Semester 1 - 2021/Machatronisches Projekt/Matlab" --include_path="E:/Documents/OneDrive - bwedu/Uni/Master/Semester 1 - 2021/Machatronisches Projekt/Matlab/RealTimeMachine_ert_rtw" --include_path="C:/Program Files/MATLAB/R2021a/extern/include" --include_path="C:/Program Files/MATLAB/R2021a/simulink/include" --include_path="C:/Program Files/MATLAB/R2021a/rtw/c/src" --include_path="C:/Program Files/MATLAB/R2021a/rtw/c/src/ext_mode/common" --include_path="C:/Program Files/MATLAB/R2021a/rtw/c/ert" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/target/supportpackages/tic2000/inc" --include_path="C:/Program Files/MATLAB/R2021a/toolbox/shared/can/src/scanutil" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/target/supportpackages/tic2000/src" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/shared/supportpackages/tic2000/src" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/shared/supportpackages/tic2000/inc" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/device_support/f28004x/common/include" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/libraries/calibration/hrpwm/f28004x/include" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/driverlib/f28004x/driverlib" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/driverlib/f28004x/driverlib/inc" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/device_support/f28004x/headers/include" --include_path="C:/ti/c2000/C2000Ware_3_04_00_00/device_support/f28004x/common" --include_path="C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/target/shared/externalmode_daemon/include" --include_path="C:/Program Files/MATLAB/R2021a/toolbox/rtw/targets/common/can/blocks/tlc_c" --define=MODEL=RealTimeMachine --define=NUMST=1 --define=NCSTATES=0 --define=HAVESTDIO --define=MODEL_HAS_DYNAMICALLY_LOADED_SFCNS=0 --define=CLASSIC_INTERFACE=0 --define=ALLOCATIONFCN=0 --define=TID01EQ=0 --define=TERMFCN=1 --define=ONESTEPFCN=1 --define=MAT_FILE=0 --define=MULTI_INSTANCE_CODE=0 --define=INTEGER_CODE=0 --define=MT=0 --define=DAEMON_MODE=1 --define=XCP_CUSTOM_PLATFORM --define=EXTMODE_DISABLE_ARGS_PROCESSING=1 --define=MW_PIL_SCIFIFOLEN=16 --define=CPU1 --define=F2837X_REG_FORMAT --define=MW_F28004X --define=STACK_SIZE=1024 --define=__MW_TARGET_USE_HARDWARE_RESOURCES_H__ --define=RT --define=F280049C --define=BOOT_FROM_FLASH=1 --abi=coffabi -s -v28 -ml --abi=coffabi  --preproc_dependency=$(@:%.obj=%.dep) --preproc_with_compile  --large_memory_model -I$(F28_HEADERS)/include -I$(TI_INCLUDE) -v28 --float_support=fpu32 -ml -DF280049C -DBOOT_FROM_FLASH=1 --tmu_support=tmu0 --fp_mode=relaxed --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '


